site_name: OutputKit
repo_url: https://github.com/nturpin0/OutputKit
nav:
  - Getting started: Getting Started.md
  - ml tags: mltags.md
  - Component tags: components.md
  - Shortcuts: shortcuts.md
  - Showcase: showcase.md
theme:
  name: readthedocs
